version: '3.9'

services:
  voip-container-1:
    image: judavalente/linphone:latest
    devices:
      - /dev/snd:/dev/snd
    environment:
      - DISPLAY=${DISPLAY}
      - PULSE_SERVER=unix:/run/user/1000/pulse:/run/user/1000/pulse/native
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /run/user/1000/pulse:/run/user/1000/pulse
    networks:
      - redeasterisk
    ports:
      - "5060:5060/udp"
      - "16384-16400:16384-16400/udp"

  voip-container-2:
    image: judavalente/linphone:latest
    devices:
      - /dev/snd:/dev/snd
    environment:
      - DISPLAY=${DISPLAY}
      - PULSE_SERVER=unix:/run/user/1000/pulse:/run/user/1000/pulse/native
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /run/user/1000/pulse:/run/user/1000/pulse
    networks:
      - redeasterisk
    ports:
      - "5061:5060/udp"
      - "16401-16417:16384-16400/udp"

  asterisk:
    image: judavalente/asterisk:latest
    volumes:
      - ./sip.conf:/etc/asterisk/sip.conf
      - ./extensions.conf:/etc/asterisk/extensions.conf
    networks:
      - redeasterisk
    ports:
      - "5063:5060/udp"

networks:
  redeasterisk:
